CREATE TABLE "service_dependencies" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "fromServiceId" TEXT NOT NULL, "toServiceId" TEXT NOT NULL, "relationship" TEXT NOT NULL DEFAULT 'DEPENDS_ON', "criticality" INTEGER NOT NULL DEFAULT 3, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "service_dependencies_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "service_dependencies_fromServiceId_toServiceId_key" ON "service_dependencies"("fromServiceId","toServiceId"); CREATE INDEX "service_dependencies_organizationId_idx" ON "service_dependencies"("organizationId");
ALTER TABLE "service_dependencies" ADD CONSTRAINT "service_dependencies_org_fk" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "service_dependencies" ADD CONSTRAINT "service_dependencies_from_fk" FOREIGN KEY ("fromServiceId") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "service_dependencies" ADD CONSTRAINT "service_dependencies_to_fk" FOREIGN KEY ("toServiceId") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "change_events" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "serviceId" TEXT, "projectId" TEXT, "type" TEXT NOT NULL DEFAULT 'DEPLOYMENT', "title" TEXT NOT NULL, "commitSha" TEXT, "author" TEXT, "source" TEXT NOT NULL DEFAULT 'MANUAL', "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "change_events_pkey" PRIMARY KEY ("id"));
CREATE INDEX "change_events_organizationId_occurredAt_idx" ON "change_events"("organizationId","occurredAt"); CREATE INDEX "change_events_serviceId_occurredAt_idx" ON "change_events"("serviceId","occurredAt");
ALTER TABLE "change_events" ADD CONSTRAINT "change_events_org_fk" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "change_events" ADD CONSTRAINT "change_events_service_fk" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "change_events" ADD CONSTRAINT "change_events_project_fk" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "service_slos" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "serviceId" TEXT NOT NULL, "targetPercent" DOUBLE PRECISION NOT NULL DEFAULT 99.9, "windowDays" INTEGER NOT NULL DEFAULT 30, "burnAlertPercent" DOUBLE PRECISION NOT NULL DEFAULT 50, "enabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "service_slos_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "service_slos_serviceId_key" ON "service_slos"("serviceId"); CREATE INDEX "service_slos_organizationId_idx" ON "service_slos"("organizationId");
ALTER TABLE "service_slos" ADD CONSTRAINT "service_slos_org_fk" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "service_slos" ADD CONSTRAINT "service_slos_service_fk" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE CASCADE;
