/**
 * V6 — generate a reproduction test from a diagnosis.
 *
 * A fix is only proven when a test fails before it and passes after it. ARCH can write the first
 * draft of that test from the stack trace and the code it saw: the failing call, the error it
 * expects, and a clear comment saying what a human must check.
 *
 * The output is deliberately a *starting point*, not a finished test: it asserts the reported
 * failure in the simplest way that can work offline (no network, no database, no fixtures), and it
 * is always reviewed by a human before it is used as evidence.
 *
 * Pure: no filesystem, no process, no database.
 */

import type { CodeLanguage } from './analyzer';
import type { ErrorDiagnosis } from './analyzer';

export type ReproductionTest = {
  /** Path the test should be written to, relative to the repository root. */
  path: string;
  source: string;
  /** What a human still has to fill in for the test to be meaningful. */
  todos: string[];
};

const MAX_SNIPPET = 600;

function safeName(text: string): string {
  const slug = text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);
  return slug || 'incident';
}

/** The first stack frame, as an importable module path when it looks like one. */
function moduleOf(file: string): string {
  return file.replace(/^\/+/, '').replace(/\.[cm]?[jt]sx?$/, '');
}

export function generateReproductionTest(params: {
  incidentTitle: string;
  language: CodeLanguage;
  diagnosis?: ErrorDiagnosis | null;
  topFrameFile?: string | null;
  /** The code the responder pasted, when they pasted code rather than a stack trace. */
  snippet?: string | null;
}): ReproductionTest {
  const name = safeName(params.incidentTitle);
  const diagnosis = params.diagnosis ?? null;
  const todos = [
    'Point the import at the real module and call the real function.',
    'Replace the placeholder input with the input that triggered the failure.',
    'Confirm the assertion matches the failure the incident reported.',
  ];

  const common = [
    `Reproduction test for: ${params.incidentTitle}`,
    diagnosis ? `Expected failure: ${diagnosis.title} — ${diagnosis.explanation}` : 'Expected failure: see the incident timeline.',
    'Generated by ARCH as a starting point. A human must review it before it counts as evidence.',
  ].join('\n// ');

  switch (params.language) {
    case 'python':
      return {
        path: `tests/test_repro_${name}.py`,
        source: `# ${common}\nimport pytest\n\n\ndef test_repro_${name.replace(/-/g, '_')}():\n    # TODO: import the module that raised and call it with the failing input.\n    # from app.service import handler\n    with pytest.raises(Exception):  # noqa: B017 - tighten to the real exception type\n        # handler(<the input that failed>)\n        raise NotImplementedError('fill in the failing call')\n`,
        todos,
      };
    case 'go':
      return {
        path: `repro_${name}_test.go`,
        source: `// ${common}\npackage main\n\nimport "testing"\n\nfunc TestRepro${name.replace(/-/g, '_')}(t *testing.T) {\n\t// TODO: call the function that failed with the input that failed.\n\t// if err := DoWork(input); err == nil {\n\t// \tt.Fatalf("expected the reported failure, got nil")\n\t// }\n\tt.Skip("fill in the failing call")\n}\n`,
        todos,
      };
    case 'java':
      return {
        path: `src/test/java/Repro${name.replace(/-/g, '_')}Test.java`,
        source: `// ${common}\nimport org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.assertThrows;\n\nclass Repro${name.replace(/-/g, '_')}Test {\n    @Test\n    void reproducesTheFailure() {\n        // TODO: call the method that threw, with the input that threw.\n        assertThrows(RuntimeException.class, () -> {\n            throw new UnsupportedOperationException("fill in the failing call");\n        });\n    }\n}\n`,
        todos,
      };
    case 'typescript':
    case 'javascript':
    default:
      return {
        path: `tests/repro-${name}.test.ts`,
        source: `// ${common}\nimport { describe, expect, it } from 'vitest';\n\n// TODO: import the module that threw, e.g.\n// import { handler } from '../src/${params.topFrameFile ? moduleOf(params.topFrameFile) : 'service'}';\n\ndescribe('reproduction: ${params.incidentTitle.replace(/\*\//g, '* /')}', () => {\n  it('fails the way the incident reported', async () => {\n    // TODO: call the real function with the input that failed.\n    await expect(Promise.reject(new Error('fill in the failing call'))).rejects.toThrow();\n  });\n});\n`,
        todos,
      };
  }
}

/** Short, human-readable explanation of what the test asserts, for the UI. */
export function describeReproduction(test: ReproductionTest): string {
  const firstLine = test.source.split('\n').find((line) => line.trim() && !line.trim().startsWith('//')) ?? '';
  return firstLine.trim().slice(0, 160);
}

export const REPRODUCTION_SNIPPET_LIMIT = MAX_SNIPPET;
