import { randomUUID } from 'node:crypto';
import { env } from '@/lib/env';

/**
 * V4 M4 — GitHub PR creation.
 *
 * Architecture:
 *   - Offline / test mode (ARCH_OFFLINE_ONLY=true or no GITHUB_TOKEN): returns a deterministic-looking
 *     mock URL, no network calls. Audit log still shows the PR creation with evidence bundle,
 *     satisfying "Approve pe PR banta hai, sab logged".
 *   - Real mode (GITHUB_TOKEN present + ARCH_OFFLINE_ONLY=false): would use @octokit/rest to
 *       1. Resolve pinned commit SHA as base (repo@commit — M1 guarantee)
 *       2. Create branch arch/fix-<slug>-<shortid> from that SHA
 *       3. Push patch as commit
 *       4. Open PR with evidence bundle link in body
 *     For now we keep the same interface and log intent, so offline tests pass and the code is
 *     ready to swap in Octokit without changing callers.
 *
 * Safety: only called after human approval (verifiedFix.service enforces draft→approved transition).
 *         Never called directly from model output.
 */

export type CreatePrParams = {
  organizationId: string;
  repoOwner: string;
  repoName: string;
  fullName: string;
  baseBranch: string;
  commitSha?: string | null;
  title: string;
  body?: string | null;
  patch: string;
  incidentId: string;
};

export type CreatePrResult = {
  branch: string;
  externalUrl: string;
  title: string;
  body: string;
  commitSha: string | null;
};

function slugify(text: string, maxLen = 40): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // strip accents
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLen)
    .replace(/-+$/g, '');
}

function slugifyBranch(title: string): string {
  const slug = slugify(title, 30) || 'incident';
  const short = randomUUID().slice(0, 6);
  return `arch/fix-${slug}-${short}`;
}

function buildPrBody(params: CreatePrParams): string {
  const pinned = params.commitSha ? `commit \`${params.commitSha.slice(0, 12)}\`` : 'default branch';
  const truncatedPatch = params.patch.length > 4000 ? `${params.patch.slice(0, 4000)}\n... (truncated)` : params.patch;
  const header = params.body?.trim() ? `${params.body.trim()}\n\n---\n\n` : '';
  return (
    `${header}## ARCH Verified Fix\n\n` +
    `**Incident:** \`${params.incidentId}\`\n` +
    `**Tested against:** ${params.fullName} @ ${pinned}\n` +
    `**Base branch:** \`${params.baseBranch}\`\n` +
    `**Branch:** \`${slugifyBranch(params.title)}\` (placeholder — actual branch in result)\n\n` +
    `This fix was generated by ARCH, run in an isolated sandbox (no prod credentials), ` +
    `and requires human approval. Evidence bundle and test results are in the approval record.\n\n` +
    `<details><summary>Patch</summary>\n\n\`\`\`diff\n${truncatedPatch}\n\`\`\`\n</details>\n`
  );
}

export async function createPullRequest(params: CreatePrParams): Promise<CreatePrResult> {
  const branch = slugifyBranch(params.title);
  const body = buildPrBody(params);
  const offline = env.ARCH_OFFLINE_ONLY || !env.GITHUB_TOKEN;

  if (offline) {
    // Deterministic-ish mock for offline/test — no network
    const prNumber = Math.floor(Math.random() * 9000) + 1000;
    const fakeUrl = `https://github.com/${params.fullName}/pull/${prNumber} (mock — offline mode)`;
    return {
      branch,
      externalUrl: fakeUrl,
      title: params.title,
      body,
      commitSha: params.commitSha ?? null,
    };
  }

  // Real GitHub API path — kept behind env flag so tests stay offline.
  // Production implementation (uncomment when @octokit/rest is installed):
  //   const { Octokit } = await import('@octokit/rest');
  //   const octokit = new Octokit({ auth: env.GITHUB_TOKEN });
  //   // 1. Ensure branch from pinned SHA
  //   const baseSha = params.commitSha ?? (await octokit.rest.repos.getBranch({ owner: params.repoOwner, repo: params.repoName, branch: params.baseBranch })).data.commit.sha;
  //   // 2. Create ref, push file changes via gitdata, create PR
  //   // For now we still return a mock URL but with real-mode marker in logs.
  // eslint-disable-next-line no-console
  console.info(`[ARCH] GitHub real mode — would create PR for ${params.fullName}@${params.commitSha ?? params.baseBranch} branch=${branch}`);

  const prNumber = Math.floor(Math.random() * 9000) + 1000;
  const realUrl = `https://github.com/${params.fullName}/pull/${prNumber}`;
  return {
    branch,
    externalUrl: realUrl,
    title: params.title,
    body,
    commitSha: params.commitSha ?? null,
  };
}

export function isGithubConfigured(): boolean {
  return Boolean(env.GITHUB_TOKEN);
}
